[phases.setup]
nixPkgsArchive = "default"
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.pdo", "php82Extensions.pdo_sqlite", "php82Extensions.openssl"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."